"❗️ migrations":
  - changed-files:
      - any-glob-to-any-file:
          - packages/db/prisma/migrations/**/migration.sql

"❗️ .env changes":
  - changed-files:
      - any-glob-to-any-file:
          - .env.example
