name: Quick Tests

permissions:
  contents: read

on:
  pull_request: # Runs BEFORE merge during PR review
    branches:
      - main # Feature branches -> main
      - release # main -> release (production)
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: warp-ubuntu-latest-arm64-4x
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: WarpBuilds/cache@v1
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-bun-quick-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-quick-
            ${{ runner.os }}-bun-

      - name: Cache Next.js build
        uses: WarpBuilds/cache@v1
        with:
          path: |
            apps/app/.next/cache
          key: ${{ runner.os }}-nextjs-quick-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('apps/app/**/*.js', 'apps/app/**/*.jsx', 'apps/app/**/*.ts', 'apps/app/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-quick-${{ hashFiles('**/bun.lock') }}-
            ${{ runner.os }}-nextjs-quick-
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Prisma Client
        run: |
          cd packages/db
          bunx prisma generate

      - name: Type check
        run: |
          cd apps/app
          bun run typecheck || true # Don't fail on type errors yet

      - name: Lint
        run: |
          cd apps/app
          bun run lint || true # Don't fail on lint errors yet

      - name: Run middleware tests (smoke test)
        run: |
          cd apps/app
          bunx vitest middleware.test.ts --run
        env:
          CI: true
          AUTH_SECRET: test-auth-secret-for-ci
          BETTER_AUTH_URL: http://localhost:3000

      - name: Check build
        run: |
          cd apps/app
          # Quick build check without full optimization
          bunx next build --experimental-build-mode=compile
        env:
          SKIP_ENV_VALIDATION: true
          DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
          AUTH_SECRET: test-secret-for-ci
          BETTER_AUTH_URL: http://localhost:3000
          # Dummy values for build to succeed
          UPSTASH_REDIS_REST_URL: https://dummy.upstash.io
          UPSTASH_REDIS_REST_TOKEN: dummy-token
          RESEND_API_KEY: dummy-resend-key
          TRIGGER_SECRET_KEY: dummy-trigger-key
