services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: comp
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d comp']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
