version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Installing dependencies..."
      - curl -fsSL https://bun.sh/install | bash

  build:
    commands:
      # Environment setup
      - export PATH="/root/.bun/bin:$PATH"
      - export PGSSLMODE=require
      - export NEXT_TELEMETRY_DISABLED=1
      - export UV_THREADPOOL_SIZE=36
      - export NODE_OPTIONS="--max-old-space-size=65536"

      # Navigate to portal directory
      - cd apps/$APP_NAME

      # Install dependencies
      - echo "Installing dependencies..."
      - SKIP_ENV_VALIDATION=true bun install --frozen-lockfile --concurrent 36 || SKIP_ENV_VALIDATION=true bun install --concurrent 36
      - cd ../../

      # Generate Prisma client
      - echo "Generating Prisma client..."
      - cd packages/db && bun x prisma generate && cd ../../

      # Validate environment variables
      - echo "Validating environment variables..."
      - '[ -n "$STATIC_ASSETS_BUCKET" ] || { echo "❌ STATIC_ASSETS_BUCKET is not set"; exit 1; }'

      # Type check (optional - skip if script doesn't exist)
      - echo "Type checking..."
      - cd apps/$APP_NAME && (bun run typecheck || echo "No typecheck script found, skipping...") && cd ../../

      # Build Next.js portal app
      - echo "Building Next.js portal application..."
      - cd apps/$APP_NAME
      - NODE_TLS_REJECT_UNAUTHORIZED=0 bun run build

      # Upload Next.js chunks and CSS to S3 for CDN performance
      - echo "Uploading Next.js static assets to S3..."
      - |
        if [ -d ".next/static" ]; then
          echo "📦 Uploading .next/static/ files to CDN..."
          aws s3 sync .next/static/ s3://$STATIC_ASSETS_BUCKET/_next/static/ \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude "*.map" \
            --delete
          echo "✅ Uploaded Next.js static assets to S3"
        else
          echo "⚠️ No .next/static directory found"
        fi

      # Upload public assets to S3 for CDN serving
      - |
        if [ -d "public" ]; then
          echo "📦 Uploading public/ files to S3..."
          aws s3 sync public/ s3://$STATIC_ASSETS_BUCKET/ \
            --cache-control "public, max-age=86400" \
            --exclude "*.map" \
            --exclude "_next/*"
          echo "✅ Uploaded public assets to S3"
        else
          echo "⚠️ No public directory found"
        fi

      # Prepare standalone build for container
      - echo "Preparing standalone build..."
      - echo "DEBUG - Checking what Next.js built..."
      - ls -la .next/
      - ls -la .next/standalone/ || echo "No standalone directory"
      - echo "DEBUG - Checking app's own .next build structure..."
      - ls -la .next/server/ || echo "No .next/server directory"
      - echo "DEBUG - Checking for server.js in various locations..."
      - test -f .next/standalone/server.js && echo "✅ Standalone server.js exists" || echo "❌ No standalone server.js"
      - find .next -name "server.js" | head -5 || echo "No server.js found anywhere"

      # Create container build directory
      - mkdir -p container-build

      # Use the standalone build properly: copy from .next/standalone + app's own build
      - echo "DEBUG - Building container from standalone + app build..."

      # Copy the app's own built files (server.js, etc.)
      - echo "Copying app's own .next build..."
      - cp -r .next container-build/ || echo "App .next copy failed"

      # Copy shared node_modules from standalone (minimal runtime deps)
      - echo "Copying standalone node_modules (runtime dependencies)..."
      - cp -r .next/standalone/node_modules container-build/ || echo "Standalone node_modules copy failed"

      # Copy or create server.js for standalone
      - |
        if [ -f ".next/standalone/apps/$APP_NAME/server.js" ]; then
          echo "Using app-specific standalone server.js..."
          cp .next/standalone/apps/$APP_NAME/server.js container-build/
        elif [ -f ".next/standalone/server.js" ]; then
          echo "Using global standalone server.js..."
          cp .next/standalone/server.js container-build/
        else
          echo "Creating minimal standalone server.js..."
          cat > container-build/server.js << 'EOF'
        const { createServer } = require('http')
        const next = require('next')

        const dev = false
        const hostname = process.env.HOSTNAME || '0.0.0.0'
        const port = process.env.PORT || 3000

        // Use the current directory as the Next.js app
        const app = next({ dev, hostname, port, dir: __dirname })
        const handle = app.getRequestHandler()

        app.prepare().then(() => {
          createServer(async (req, res) => {
            await handle(req, res)
          }).listen(port, hostname, () => {
            console.log(`> Ready on http://${hostname}:${port}`)
          })
        })
        EOF
        fi

      # Verify the standalone build
      - echo "DEBUG - Verifying standalone build..."
      - ls -la container-build/
      - test -f container-build/server.js && echo "✅ Server.js exists" || echo "❌ Server.js missing"
      - test -d container-build/.next && echo "✅ .next directory exists" || echo "❌ .next directory missing"
      - test -d container-build/node_modules && echo "✅ node_modules exists" || echo "❌ node_modules missing"

      # Add Dockerfile to the standalone build
      - cp Dockerfile container-build/ || echo "No Dockerfile"

      # Ensure Prisma client is available (override standalone if needed)
      - echo "Ensuring Prisma client is available..."
      - mkdir -p container-build/node_modules/.prisma container-build/node_modules/@prisma
      - |
        if [ -d "../../node_modules/.prisma/client" ]; then
          echo "Copying Prisma client from monorepo root..."
          cp -r ../../node_modules/.prisma/client container-build/node_modules/.prisma/
        elif [ -d "node_modules/.prisma/client" ]; then
          echo "Copying Prisma client from app directory..."
          cp -r node_modules/.prisma/client container-build/node_modules/.prisma/
        else
          echo "Warning: No Prisma client found"
        fi
      - |
        if [ -d "../../node_modules/@prisma/client" ]; then
          echo "Copying @prisma/client from monorepo root..."
          cp -r "../../node_modules/@prisma/client" "container-build/node_modules/@prisma/"
        elif [ -d "node_modules/@prisma/client" ]; then
          echo "Copying @prisma/client from app directory..."
          cp -r "node_modules/@prisma/client" "container-build/node_modules/@prisma/"
        else
          echo "Warning: No @prisma/client found"
        fi

      # Debug: Verify container build contents
      - echo "DEBUG - Verifying app-specific container build..."
      - ls -la container-build/
      - ls -la container-build/.next/ || echo "❌ .next directory not found"
      - ls -la container-build/node_modules/next/ || echo "❌ Next.js module not found"
      - ls -la container-build/node_modules/.prisma/ || echo "❌ Prisma client not found"
      - test -f container-build/server.js && echo "✅ App-specific server.js found" || echo "❌ App-specific server.js not found"
      - head -10 container-build/server.js || echo "❌ Cannot read server.js"

      # Build Docker image (static assets now served from S3)
      - echo "Building Docker image..."
      - docker build --build-arg BUILDKIT_INLINE_CACHE=1 -f container-build/Dockerfile -t $ECR_REPOSITORY_URI:$IMAGE_TAG container-build/
      - docker tag $ECR_REPOSITORY_URI:$IMAGE_TAG $ECR_REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI:latest
      - echo "Updating ECS service..."
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
      - 'printf "[{\"name\":\"%s-container\",\"imageUri\":\"%s\"}]" $APP_NAME $ECR_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json'

cache:
  paths:
    - 'node_modules/**/*'
    - 'packages/db/node_modules/**/*'
    - '/root/.bun/install/cache/**/*'
    - '.next/cache/**/*'
    - 'bun.lock'

artifacts:
  files:
    - imagedefinitions.json
  name: ${APP_NAME}-build
