name: Github Releases To Discord

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    permissions:
      contents: read
    runs-on: warp-ubuntu-latest-arm64-4x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
