name: Deploy Website

on:
  push:
    branches:
      - '**'
    paths:
      - apps/app/**

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Languine Action
        uses: languine-ai/languine@v.1.0.0
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          api-key: ${{ secrets.LANGUINE_API_KEY }}
          project-id: ${{ secrets.LANGUINE_PROJECT_ID }}