name: Deploy Website

on:
  push:
    branches:
      - "**"
    paths:
      - apps/app/**

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      # Backup non-English translation files to prevent processing
      - name: Backup non-English translation files
        run: |
          mkdir -p /tmp/locales-backup
          find apps/app/src/locales -maxdepth 1 -type f -name "*.ts" ! -name "en.ts" ! -name "analyze-locale-usage.ts" ! -name "client.ts" ! -name "server.ts" -exec cp {} /tmp/locales-backup/ \;
          # Temporarily remove them to prevent Languine from processing them
          find apps/app/src/locales -maxdepth 1 -type f -name "*.ts" ! -name "en.ts" ! -name "analyze-locale-usage.ts" ! -name "client.ts" ! -name "server.ts" -exec rm -f {} \;

      - name: Languine Action
        uses: languine-ai/languine@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          api-key: ${{ secrets.LANGUINE_API_KEY }}
          project-id: ${{ secrets.LANGUINE_PROJECT_ID }}
          working-directory: apps/app

      # Restore non-English translation files
      - name: Restore non-English translation files
        run: |
          cp /tmp/locales-backup/*.ts apps/app/src/locales/ || true
