name: Deploy to Trigger.dev (dev)
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest-custom
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # Updated to match Node.js w/ Vercel
      - name: Generate Prisma client
        working-directory: ./packages/db
        run: npx prisma generate
      - name: 🚀 Deploy Trigger.dev
        working-directory: ./apps/app
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: npx trigger.dev@latest deploy --env staging
