name: Unit Tests

on:
  pull_request: # Runs BEFORE merge during PR review
    branches:
      - main # Feature branches -> main
      - release # main -> release (production)
    paths:
      - 'apps/**'
      - 'packages/**'
      - '!**/*.md'
  push: # Also runs AFTER merge to main/release
    branches:
      - main
      - release
  workflow_dispatch: # Allow manual triggering

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest-custom
    timeout-minutes: 10

    strategy:
      matrix:
        app: [app, framework-editor, portal, trust]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run unit tests for ${{ matrix.app }}
        run: |
          cd apps/${{ matrix.app }}
          if [ -f "vitest.config.mts" ] || [ -f "vitest.config.ts" ]; then
            bun run test --run --reporter=json --reporter=default --outputFile=test-results.json
          else
            echo "No vitest config found, skipping tests for ${{ matrix.app }}"
          fi
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.app }}
          path: apps/${{ matrix.app }}/test-results.json
          if-no-files-found: ignore
